language: go

go:
    - 1.7
    - 1.8

install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get github.com/govend/govend
    - govend -l

script:
    - go test -coverprofile=profile.cov
    - goveralls -coverprofile=profile.cov -service=travis-ci
